# Generated by Django 4.2 on 2024-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rotation', models.IntegerField(null=True)),
                ('yellow', models.IntegerField(null=True)),
                ('red', models.IntegerField(null=True)),
                ('blue', models.IntegerField(null=True)),
                ('divine', models.IntegerField(null=True)),
                ('map_type', models.CharField(max_length=100)),
                ('map_count', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
