# Generated by Django 4.2 on 2024-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farming',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
