# Generated by Django 4.2 on 2024-10-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_farming_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='farming',
            name='net_per_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='farming',
            name='blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farming',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farming',
            name='divine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farming',
            name='map_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farming',
            name='red',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farming',
            name='yellow',
            field=models.IntegerField(default=0),
        ),
    ]
